"""added token blocklist

Revision ID: 05080bbfccad
Revises: 32839491a69b
Create Date: 2025-06-16 17:07:51.672858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05080bbfccad'
down_revision = '32839491a69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
